# Generated by Django 5.2.8 on 2025-12-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Utente ApexGPS",
                "verbose_name_plural": "Utenti ApexGPS",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="I gruppi a cui appartiene questo utente. Un utente otterrà tutti i permessi assegnati a ciascuno dei suoi gruppi.",
                related_name="custom_user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="Gruppi",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("VISITOR", "Visitatore (Non autenticato)"),
                    ("SUBSCRIBED", "Utente Registrato"),
                    ("ADMIN", "Amministratore"),
                ],
                default="SUBSCRIBED",
                max_length=20,
                verbose_name="Ruolo Utente",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permessi specifici per questo utente.",
                related_name="custom_user_permissions",
                related_query_name="user",
                to="auth.permission",
                verbose_name="Permessi utente",
            ),
        ),
    ]
