# Generated by Django 5.2.8 on 2026-02-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='URL della foto profilo da Google', max_length=500, null=True, verbose_name='Foto Profilo'),
        ),
    ]
