# Generated by Django 5.2.8 on 2026-02-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hiddenUntil',
            field=models.DateTimeField(blank=True, help_text='Data e ora per privatizzare', null=True, verbose_name='hiddenUntil '),
        ),
    ]
