# Generated by Django 5.2.8 on 2025-12-08 16:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome percorso"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Privato"),
                            ("public", "Pubblico"),
                            ("link", "Condiviso con link"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="Visibilità",
                    ),
                ),
                (
                    "start_location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Punto di partenza"
                    ),
                ),
                (
                    "end_location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Punto di arrivo"
                    ),
                ),
                (
                    "preference",
                    models.CharField(
                        choices=[
                            ("fast", "Veloce"),
                            ("balanced", "Equilibrata"),
                            ("most_winding", "Sinuosa Massima"),
                        ],
                        max_length=20,
                        verbose_name="Preferenza",
                    ),
                ),
                ("polyline", models.TextField(verbose_name="Polilinea codificata")),
                ("distance_km", models.FloatField(verbose_name="Distanza (km)")),
                (
                    "estimated_time_min",
                    models.IntegerField(verbose_name="Tempo stimato (minuti)"),
                ),
                (
                    "total_scenic_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Punteggio panoramico totale",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data aggiornamento"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Proprietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Percorso",
                "verbose_name_plural": "Percorsi",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "visibility"],
                        name="routes_rout_owner_i_5f174a_idx",
                    ),
                    models.Index(
                        fields=["visibility"], name="routes_rout_visibil_0f321a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="routes_rout_created_31febf_idx"
                    ),
                ],
            },
        ),
    ]
