# Generated by Django 5.2.8 on 2025-12-14 12:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Posizione nella sequenza (1 = prima tappa dopo la partenza)",
                        verbose_name="Ordine",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Posizione"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Nome descrittivo della tappa",
                        max_length=255,
                        verbose_name="Nome tappa (opzionale)",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data aggiunta"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="routes.route",
                        verbose_name="Percorso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tappa",
                "verbose_name_plural": "Tappe",
                "ordering": ["route", "order"],
                "indexes": [
                    models.Index(
                        fields=["route", "order"], name="routes_stop_route_i_dd5e92_idx"
                    )
                ],
                "unique_together": {("route", "order")},
            },
        ),
    ]
