# Generated by Django 5.2.8 on 2026-01-08 14:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0002_stop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="distance_km",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Distanza totale del percorso in chilometri",
                null=True,
                verbose_name="Distanza (km)",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="end_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Punto di arrivo del percorso",
                null=True,
                srid=4326,
                verbose_name="Punto di arrivo",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="estimated_time_min",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Tempo di percorrenza stimato in minuti",
                null=True,
                verbose_name="Tempo stimato (minuti)",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="polyline",
            field=models.TextField(
                blank=True,
                help_text="Rappresentazione codificata del percorso per le mappe",
                null=True,
                verbose_name="Polilinea codificata",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="preference",
            field=models.CharField(
                choices=[
                    ("fast", "Veloce"),
                    ("balanced", "Equilibrata"),
                    ("most_winding", "Sinuosa Massima"),
                ],
                default="balanced",
                max_length=20,
                verbose_name="Preferenza",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="start_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Punto di partenza del percorso",
                null=True,
                srid=4326,
                verbose_name="Punto di partenza",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="total_scenic_score",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Punteggio panoramico totale del percorso",
                null=True,
                verbose_name="Punteggio panoramico totale",
            ),
        ),
    ]
