# Generated by Django 5.2.8 on 2026-02-21 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_route_distance_km_alter_route_end_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='fingerprint',
            field=models.CharField(blank=True, help_text='Hash dei dati del percorso per rilevare duplicati', max_length=64, null=True, verbose_name='Impronta univoca'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('owner', 'fingerprint'), name='unique_route_per_owner_fingerprint'),
        ),
    ]
