# Generated by Django 5.2.8 on 2026-02-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_route_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Immagine statica della mappa con il percorso tracciato', null=True, upload_to='route_screenshots/', verbose_name='Screenshot del percorso'),
        ),
    ]
