# Generated by Django 5.2.8 on 2026-02-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_route_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='hiddenUntil',
            field=models.DateTimeField(blank=True, help_text='Data e ora per privatizzazione tour', null=True, verbose_name='hiddenUntil '),
        ),
    ]
