# Generated by Django 5.2.8 on 2026-03-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_route_hiddenuntil'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_location_name',
            field=models.CharField(blank=True, help_text='Nome del punto di arrivo', max_length=255, null=True, verbose_name='Nome arrivo'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_location_name',
            field=models.CharField(blank=True, help_text='Nome del punto di partenza', max_length=255, null=True, verbose_name='Nome partenza'),
        ),
        migrations.AlterField(
            model_name='route',
            name='hiddenUntil',
            field=models.DateTimeField(blank=True, help_text='Data e ora per privatizzazione tour', null=True, verbose_name='hiddenUntil'),
        ),
    ]
