# Generated by Django 5.2.8 on 2025-12-11 16:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DEMTile",
            fields=[
                ("rid", models.AutoField(primary_key=True, serialize=False)),
                ("rast", django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Modello elevazione terreno",
                "verbose_name_plural": "Modello elevazione terreni",
            },
        ),
        migrations.CreateModel(
            name="ElevationQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("elevation", models.FloatField(blank=True, null=True)),
                ("queried_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Elevation Query",
                "verbose_name_plural": "Elevation Queries",
                "ordering": ["-queried_at"],
            },
        ),
    ]
