# Generated by Django 5.2.8 on 2025-12-11 09:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis_data", "0002_roadsegment_alter_pointofinterest_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointofinterest",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Coordinate geografiche in formato WGS84 (latitudine, longitudine)",
                srid=4326,
                verbose_name="Posizione GPS",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="cost_scenic",
            field=models.FloatField(
                default=0.0,
                help_text="Costo per l'ottimizzazione panoramica",
                verbose_name="Costo Panoramico",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="cost_time",
            field=models.FloatField(
                default=0.0,
                help_text="Costo basato sul tempo di percorrenza stimato",
                verbose_name="Costo per Tempo",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="curvature",
            field=models.FloatField(
                default=1.0,
                help_text="Rapporto tra lunghezza effettiva e distanza in linea d'aria (≥1.0)",
                verbose_name="Sinuosità",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="elevation_gain",
            field=models.FloatField(
                default=0.0,
                help_text="Guadagno totale di elevazione lungo il segmento",
                verbose_name="Dislivello Positivo (metri)",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="geometry",
            field=django.contrib.gis.db.models.fields.LineStringField(
                help_text="Percorso della strada in formato LineString",
                srid=4326,
                verbose_name="Tracciato",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="highway",
            field=models.CharField(
                blank=True,
                help_text="Classificazione secondo lo standard OpenStreetMap",
                max_length=50,
                null=True,
                verbose_name="Tipo di Strada",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="lanes",
            field=models.IntegerField(
                blank=True,
                help_text="Numero totale di corsie (entrambi i sensi)",
                null=True,
                verbose_name="Numero di Corsie",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="length_m",
            field=models.FloatField(
                default=0.0,
                help_text="Lunghezza effettiva del segmento in metri",
                verbose_name="Lunghezza (metri)",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Nome ufficiale o comune della strada",
                max_length=255,
                null=True,
                verbose_name="Nome della Strada",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="osm_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Identificativo originale da OpenStreetMap",
                null=True,
                verbose_name="ID OpenStreetMap",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="poi_density",
            field=models.FloatField(
                default=0.0,
                help_text="Numero di punti di interesse per chilometro",
                verbose_name="Densità di Punti di Interesse",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="scenic_rating",
            field=models.FloatField(
                default=5.0,
                help_text="Punteggio di qualità panoramica da 0.0 a 10.0",
                verbose_name="Valutazione Panoramica",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="source",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID del nodo di partenza nel grafo di routing",
                null=True,
                verbose_name="Nodo di Partenza",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="target",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID del nodo di arrivo nel grafo di routing",
                null=True,
                verbose_name="Nodo di Arrivo",
            ),
        ),
        migrations.AlterField(
            model_name="scenicarea",
            name="bonus_value",
            field=models.FloatField(
                default=1.0,
                help_text="Moltiplicatore per il punteggio panoramico (es. 1.5 per +50%)",
                verbose_name="Valore Bonus",
            ),
        ),
    ]
