# Generated by Django 5.2.8 on 2025-12-24 11:30

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis_data", "0003_alter_pointofinterest_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pointofinterest",
            options={
                "ordering": ["name"],
                "verbose_name": "Punto di Interesse",
                "verbose_name_plural": "Punti di Interesse",
            },
        ),
        migrations.AlterModelOptions(
            name="roadsegment",
            options={
                "ordering": ["id"],
                "verbose_name": "Segmento Stradale",
                "verbose_name_plural": "Segmenti Stradali",
            },
        ),
        migrations.AlterModelOptions(
            name="scenicarea",
            options={
                "ordering": ["name"],
                "verbose_name": "Area Scenica",
                "verbose_name_plural": "Aree Sceniche",
            },
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data creazione",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="elevation",
            field=models.FloatField(
                blank=True,
                help_text="Altitudine sul livello del mare in metri",
                null=True,
                verbose_name="Altitudine (m)",
            ),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="importance_score",
            field=models.FloatField(
                default=1.0,
                help_text="Peso del POI nel calcolo panoramico (1.0 = normale, 2.0 = doppio)",
                verbose_name="Punteggio Importanza",
            ),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica se il POI è attivo e utilizzabile nei calcoli",
                verbose_name="Attivo",
            ),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indica se il POI è stato verificato manualmente",
                verbose_name="Verificato",
            ),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="osm_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Identificativo originale da OpenStreetMap",
                null=True,
                unique=True,
                verbose_name="ID OpenStreetMap",
            ),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="tags",
            field=models.JSONField(
                blank=True,
                help_text="Tag originali da OpenStreetMap in formato JSON",
                null=True,
                verbose_name="Tag OSM",
            ),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data aggiornamento"
            ),
        ),
        migrations.AddField(
            model_name="roadsegment",
            name="avg_elevation",
            field=models.FloatField(
                blank=True,
                help_text="Altitudine media sul livello del mare",
                null=True,
                verbose_name="Altitudine Media (m)",
            ),
        ),
        migrations.AddField(
            model_name="roadsegment",
            name="cost_balanced",
            field=models.FloatField(
                default=0.0,
                help_text="Costo per l'ottimizzazione bilanciata (50/50)",
                verbose_name="Costo Bilanciato",
            ),
        ),
        migrations.AddField(
            model_name="roadsegment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data creazione",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roadsegment",
            name="elevation_loss",
            field=models.FloatField(
                default=0.0,
                help_text="Perdita totale di elevazione lungo il segmento",
                verbose_name="Dislivello Negativo (metri)",
            ),
        ),
        migrations.AddField(
            model_name="roadsegment",
            name="hairpin_count",
            field=models.IntegerField(
                default=0,
                help_text="Numero di curve a gomito strette (≤30m raggio)",
                verbose_name="Numero di Tornanti",
            ),
        ),
        migrations.AddField(
            model_name="roadsegment",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica se il segmento è attivo per il routing",
                verbose_name="Attivo",
            ),
        ),
        migrations.AddField(
            model_name="roadsegment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data aggiornamento"
            ),
        ),
        migrations.AddField(
            model_name="roadsegment",
            name="weighted_poi_density",
            field=models.FloatField(
                default=0.0,
                help_text="Densità di POI ponderata per importanza",
                verbose_name="Densità POI Ponderata",
            ),
        ),
        migrations.AddField(
            model_name="scenicarea",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data creazione",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scenicarea",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Informazioni dettagliate sull'area scenica",
                null=True,
                verbose_name="Descrizione",
            ),
        ),
        migrations.AddField(
            model_name="scenicarea",
            name="osm_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Identificativo originale da OpenStreetMap",
                null=True,
                unique=True,
                verbose_name="ID OpenStreetMap",
            ),
        ),
        migrations.AddField(
            model_name="scenicarea",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data aggiornamento"
            ),
        ),
        migrations.AlterField(
            model_name="pointofinterest",
            name="category",
            field=models.CharField(
                choices=[
                    ("panoramic", "Panoramico"),
                    ("mountain_pass", "Passo di Montagna"),
                    ("twisty_road", "Strada con Curve"),
                    ("biker_meeting", "Ritrovo Motociclisti"),
                    ("viewpoint", "Punto di Osservazione"),
                    ("lake", "Lago"),
                    ("sea", "Mare"),
                    ("monument", "Monumento"),
                    ("historic", "Sito Storico"),
                    ("nature", "Area Naturale"),
                    ("food", "Ristorante Tipico"),
                    ("accommodation", "Alloggio Moto-friendly"),
                    ("gas_station", "Stazione di Servizio"),
                    ("technical_point", "Punto Tecnico (ponte/tunnel)"),
                    ("church", "Chiesa/Santuario"),
                    ("castle", "Castello/Fortezza"),
                    ("vineyard", "Cantina/Vigneto"),
                    ("waterfall", "Cascata"),
                    ("thermal", "Terme/Sorgente"),
                    ("museum", "Museo"),
                ],
                help_text="Classificazione del punto di interesse",
                max_length=50,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="pointofinterest",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Coordinate geografiche in formato WGS84 (longitudine, latitudine)",
                srid=4326,
                verbose_name="Posizione GPS",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="osm_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Identificativo originale da OpenStreetMap",
                null=True,
                verbose_name="ID OpenStreetMap",
            ),
        ),
        migrations.AlterField(
            model_name="scenicarea",
            name="area_type",
            field=models.CharField(
                choices=[
                    ("national_park", "Parco Nazionale"),
                    ("regional_park", "Parco Regionale"),
                    ("lake_district", "Distretto Lacustre"),
                    ("mountain_range", "Catena Montuosa"),
                    ("coastal_area", "Area Costiera"),
                    ("vineyard_area", "Zona Vinicola"),
                    ("historic_center", "Centro Storico"),
                    ("natural_reserve", "Riserva Naturale"),
                ],
                help_text="Classificazione dell'area scenica",
                max_length=50,
                verbose_name="Tipo di Area",
            ),
        ),
        migrations.AddIndex(
            model_name="pointofinterest",
            index=models.Index(fields=["osm_id"], name="gis_data_po_osm_id_f734d1_idx"),
        ),
        migrations.AddIndex(
            model_name="pointofinterest",
            index=models.Index(
                fields=["is_active"], name="gis_data_po_is_acti_139702_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointofinterest",
            index=models.Index(
                fields=["location"], name="gis_data_po_locatio_cac1b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadsegment",
            index=models.Index(
                fields=["curvature"], name="gis_data_ro_curvatu_dde5bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadsegment",
            index=models.Index(
                fields=["poi_density"], name="gis_data_ro_poi_den_3abbec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadsegment",
            index=models.Index(
                fields=["is_active"], name="gis_data_ro_is_acti_4c096d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadsegment",
            index=models.Index(fields=["osm_id"], name="gis_data_ro_osm_id_d0922b_idx"),
        ),
        migrations.AddIndex(
            model_name="scenicarea",
            index=models.Index(
                fields=["area_type"], name="gis_data_sc_area_ty_5be39a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scenicarea",
            index=models.Index(
                fields=["bonus_value"], name="gis_data_sc_bonus_v_a03b36_idx"
            ),
        ),
    ]
