# Generated by Django 5.2.8 on 2026-01-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis_data", "0004_alter_pointofinterest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadsegment",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Regione italiana a cui appartiene il segmento",
                max_length=100,
                null=True,
                verbose_name="Regione",
            ),
        ),
        migrations.AddIndex(
            model_name="roadsegment",
            index=models.Index(fields=["region"], name="gis_data_ro_region_483e47_idx"),
        ),
    ]
