# Generated by Django 5.2.8 on 2026-01-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis_data", "0005_roadsegment_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointofinterest",
            name="region",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Regione italiana di appartenenza",
                max_length=50,
                null=True,
                verbose_name="Regione",
            ),
        ),
        migrations.AlterField(
            model_name="roadsegment",
            name="region",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Regione italiana di appartenenza del segmento",
                max_length=50,
                null=True,
                verbose_name="Regione",
            ),
        ),
        migrations.AddIndex(
            model_name="pointofinterest",
            index=models.Index(fields=["region"], name="gis_data_po_region_280e95_idx"),
        ),
    ]
