# Generated by Django 5.2.8 on 2026-02-07 01:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0006_pointofinterest_region_alter_roadsegment_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsegment',
            name='old_id',
            field=models.BigIntegerField(blank=True, help_text='Link to original road segment before noded network creation', null=True, verbose_name='Original Segment ID'),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='x1',
            field=models.FloatField(blank=True, help_text='Start X coordinate for A* algorithm optimization', null=True, verbose_name='X Coordinate Start'),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='x2',
            field=models.FloatField(blank=True, help_text='End X coordinate for A* algorithm optimization', null=True, verbose_name='X Coordinate End'),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='y1',
            field=models.FloatField(blank=True, help_text='Start Y coordinate for A* algorithm optimization', null=True, verbose_name='Y Coordinate Start'),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='y2',
            field=models.FloatField(blank=True, help_text='End Y coordinate for A* algorithm optimization', null=True, verbose_name='Y Coordinate End'),
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='source',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID del nodo di partenza nel grafo di routing', null=True, verbose_name='Nodo di Partenza'),
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='target',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID del nodo di arrivo nel grafo di routing', null=True, verbose_name='Nodo di Arrivo'),
        ),
        migrations.CreateModel(
            name='RoadSegmentNoded',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('old_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Original Segment ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome della Strada')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Tracciato')),
                ('length_m', models.FloatField(default=0.0, verbose_name='Lunghezza (metri)')),
                ('cost_length', models.FloatField(default=0.0, verbose_name='Costo per Lunghezza')),
                ('cost_time', models.FloatField(default=0.0, verbose_name='Costo per Tempo')),
                ('cost_scenic', models.FloatField(default=0.0, verbose_name='Costo Panoramico')),
                ('cost_balanced', models.FloatField(default=0.0, verbose_name='Costo Bilanciato')),
                ('source', models.BigIntegerField(db_index=True, verbose_name='Nodo di Partenza')),
                ('target', models.BigIntegerField(db_index=True, verbose_name='Nodo di Arrivo')),
                ('x1', models.FloatField(blank=True, null=True)),
                ('y1', models.FloatField(blank=True, null=True)),
                ('x2', models.FloatField(blank=True, null=True)),
                ('y2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Segmento Stradale (Noded)',
                'verbose_name_plural': 'Segmenti Stradali (Noded)',
                'db_table': 'road_segment_noded',
                'indexes': [models.Index(fields=['source', 'target'], name='road_segmen_source_33733c_idx'), models.Index(fields=['source'], name='road_segmen_source_bf1435_idx'), models.Index(fields=['target'], name='road_segmen_target_1f7d57_idx'), models.Index(fields=['old_id'], name='road_segmen_old_id_fb069f_idx')],
            },
        ),
    ]
