# Generated by Django 5.2.8 on 2026-02-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0007_roadsegment_old_id_roadsegment_x1_roadsegment_x2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsegmentnoded',
            name='source',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Nodo di Partenza'),
        ),
        migrations.AlterField(
            model_name='roadsegmentnoded',
            name='target',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Nodo di Arrivo'),
        ),
    ]
