# Generated by Django 5.2.8 on 2026-03-11 09:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0008_alter_roadsegmentnoded_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Nome ufficiale del comune', max_length=100, verbose_name='Nome Comune')),
                ('province', models.CharField(blank=True, help_text='Nome della provincia di appartenenza', max_length=100, null=True, verbose_name='Provincia')),
                ('province_code', models.CharField(blank=True, help_text='Sigla automobilistica della provincia (es. RM, MI, NA)', max_length=2, null=True, verbose_name='Sigla Provincia')),
                ('region', models.CharField(db_index=True, help_text='Regione italiana di appartenenza (corrisponde a OSMConfig.ALL_REGIONS)', max_length=50, verbose_name='Regione')),
                ('istat_code', models.CharField(help_text='Codice ISTAT ufficiale del comune', max_length=10, unique=True, verbose_name='Codice ISTAT')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Coordinate del centro città (di solito il municipio)', srid=4326, verbose_name='Centro Città')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Confini amministrativi del comune', null=True, srid=4326, verbose_name='Confini Comunali')),
                ('population', models.IntegerField(blank=True, help_text='Numero di abitanti (fonte ISTAT)', null=True, verbose_name='Popolazione')),
                ('elevation', models.FloatField(blank=True, help_text='Altitudine sul livello del mare in metri', null=True, verbose_name='Altitudine (m)')),
                ('osm_id', models.BigIntegerField(blank=True, help_text='Identificativo originale da OpenStreetMap', null=True, unique=True, verbose_name='ID OpenStreetMap')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aggiornamento')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se il comune è attivo per le ricerche', verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Comune',
                'verbose_name_plural': 'Comuni',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='gis_data_ci_name_2407ff_idx'), models.Index(fields=['region'], name='gis_data_ci_region_d28e1b_idx'), models.Index(fields=['province'], name='gis_data_ci_provinc_d88f32_idx'), models.Index(fields=['province_code'], name='gis_data_ci_provinc_1fc049_idx'), models.Index(fields=['istat_code'], name='gis_data_ci_istat_c_19a502_idx'), models.Index(fields=['location'], name='gis_data_ci_locatio_cfea08_idx')],
            },
        ),
    ]
