# Generated by Django 5.2.8 on 2026-02-22 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0008_alter_roadsegmentnoded_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegmentPOIRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_m', models.FloatField(help_text='Distance from POI to road segment in meters', verbose_name='Distance (meters)')),
                ('is_within_max_distance', models.BooleanField(db_index=True, default=True, help_text='Whether this POI is within the maximum configured distance', verbose_name='Within Max Distance')),
                ('scenic_value_cache', models.FloatField(default=0.0, help_text='Pre-calculated scenic value for this POI-segment pair', verbose_name='Cached Scenic Value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_relations', to='gis_data.pointofinterest', verbose_name='Point of Interest')),
                ('road_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poi_relations', to='gis_data.roadsegment', verbose_name='Road Segment')),
            ],
            options={
                'verbose_name': 'Road Segment-POI Relation',
                'verbose_name_plural': 'Road Segment-POI Relations',
                'indexes': [models.Index(fields=['road_segment', 'is_within_max_distance', 'scenic_value_cache'], name='gis_data_ro_road_se_707e2a_idx'), models.Index(fields=['poi', 'is_within_max_distance'], name='gis_data_ro_poi_id_7276c3_idx'), models.Index(fields=['scenic_value_cache'], name='gis_data_ro_scenic__d3a64a_idx')],
                'unique_together': {('road_segment', 'poi')},
            },
        ),
    ]
