# Generated by Django 5.2.8 on 2026-03-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0009_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='istat_code',
            field=models.CharField(blank=True, help_text='Codice ISTAT ufficiale del comune', max_length=10, null=True, unique=True, verbose_name='Codice ISTAT'),
        ),
    ]
